name: 'Netlify Actions'
description: 'GitHub Actions for Netlify'
author: 'Ryo Ota'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
