name: 'Netlify Actions'
description: 'Netlify deploy from GitHub Actions'
author: 'Ryo Ota'
inputs:
  publish-dir:
    description: Publish directory
    required: true
  github-token:
    description: GitHub token
    required: false
  production-branch:
      description: Production branch
      required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
