name: 'Netlify Actions'
description: 'GitHub Actions for Netlify'
author: 'Ryo Ota'
inputs:
  publish-dir:
    description: Publish directory
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
